# nave
DECREASE_ENEMY_SPEED = 0
HEAL = 1
KILL_ALL = 2
SIDE_SHOT = 3
INCREASE_SPEED = 4
SHIELD_UP = 5

# tetris
BLOCKED_BAR = 0
ERASE_BOTTOM = 1
NEW_PIECE = 2
DECREASE_GRAVITY = 3
INCREASE_ENEMY_GRAVITY = 4
CLEAR_GRID = 5